version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    domainname: ${DOMAIN_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}


    ports:
      - 8123:8123
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      ## HTTP Routers
      - "traefik.http.routers.homeassistant-secure.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-secure.rule=Host(`$DOMAIN_NAME`)"
        #      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.routers.homeassistant-secure.tls.certresolver=letsencrypt"
        #- "traefik.http.routers.jellyfin-secure.middlewares=secureHeaders@file"

      ## Middlewares
      - "traefik.http.middlewares.custom.headers.sslredirect=true"

      ## HTTP Services
      - "traefik.http.services.homeassistant-secure.loadbalancer.server.port=80"

    volumes:
      - config:/config
        #restart: always
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true

volumes:
  config:
